baseURL: "https://chobobdev.github.io/"
languageCode: "en-us"
title: "Chobobdev"


module:
  # uncomment line below for temporary local development of module
  # replacements: "github.com/CaiJimmy/hugo-theme-stack/v3 -> ../../hugo-theme-stack"
  imports:
    - path: github.com/CaiJimmy/hugo-theme-stack/v3
      disable: false

permalinks:
    post: /p/:slug/
    page: /:slug/

DefaultContentLanguage: en

params:
  dateFormat:
      published: Jan 02, 2006
      lastUpdated: Jan 02, 2006 15:04 MST

  sidebar:
      subtitle: "Backend Developer"
      emoji: 🍕
      avatar:
          enabled: true
          local: true
          src: /img/avatar.png
  widgets:
      homepage:
          - type: search
          - type: categories
            params:
                limit: 10
          - type: tag-cloud
            params:
                limit: 10
  comments:
      enabled: true
      provider: utterances

      utterances:
        repo: chobobdev/chobobdev.github.io
        issueTerm: pathname
        label:

  
menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          params:
            icon: home

    social:
        - identifier: github
          name: GitHub
          url: https://github.com/Chobobdev
          params:
              icon: brand-github
