baseURL: "https://chobobdev.github.io/"
languageCode: "en"
title: "chobobdev"
enableRobotsTXT: true
module:
  # uncomment line below for temporary local development of module
  # replacements: "github.com/CaiJimmy/hugo-theme-stack/v3 -> ../../hugo-theme-stack"
  imports:
    - path: github.com/CaiJimmy/hugo-theme-stack/v3
      disable: false

params:
  widgets:
    homepage:
        - type: search
        - type: archives
          params:
              limit: 5
        - type: categories
          params:
              limit: 10
        - type: tag-cloud
          params:
              limit: 10
menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          params:
            icon: home

        - identifier: about
          name: About
          url: /about
          weight: -90
          params:
            icon: user
        
        - identifier: search
          name: Search
          url: /Search
          weight: -80
          params:
            icon: search