baseURL: "https://chobobdev.github.io/"
languageCode: "en-us"
title: "Chobobdev"


module:
  imports:
    - path: github.com/CaiJimmy/hugo-theme-stack/v3
      disable: false

permalinks:
    post: /p/:slug/
    page: /:slug/

DefaultContentLanguage: en

googleAnalytics: G-F6BNXT2DDH

params:
  favicon: /favicon.ico
  footer:
      since: 2022
      customText: Shark attack
  dateFormat:
      published: Jan 02, 2006
      lastUpdated: Jan 02, 2006 15:04 MST

  sidebar:
      subtitle: "Backend Developer"
      emoji: 🍕
      avatar:
          enabled: true
          local: true
          src: /img/avatar_2023.png
  widgets:
      homepage:
          - type: search
          - type: categories
            params:
                limit: 10
          - type: tag-cloud
            params:
                limit: 10
      page:
          - type: toc
  comments:
      enabled: true
      provider: utterances

      utterances:
        repo: chobobdev/chobobdev.github.io
        issueTerm: pathname
        label:
  article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: false
            default: Licensed under CC BY-NC-SA 4.0

  
menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          params:
            icon: home

    social:
        - identifier: github
          name: GitHub
          url: https://github.com/Chobobdev
          params:
              icon: brand-github

        - identifier: linkedin
          name: LinkedIn
          url: https://www.linkedin.com/in/seongbin-cho-120641170/
          params:
              icon: linkedin

markup:
  highlight: 
    noClasses: false
