name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}
          submodules: recursive


      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo


      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          token: ${{ secrets.TOKEN }}
          external_repository: chobobdev/chobobdev.github.io
          publish_branch: gh-pages  # default: gh-pages
          publish_dir: ./public
